export const FETCH_CONTAINERS = 'FETCH_CONTAINERS';
export const FETCH_VESSELS = 'FETCH_VESSELS';
export const FETCH_VESSEL_PLANS = 'FETCH_VESSEL_PLANS';
export const UPDATE_VESSELS = 'UPDATE_VESSELS';